import assert from "node:assert/strict";
import {test} from "node:test";
import {mkdtemp,rm,readFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {execFileSync} from "node:child_process";
import {DatabaseSync} from "node:sqlite";
import {SqlitePiboSessionStore} from "../dist/sessions/sqlite-store.js";
import {PiboDataSessionStore} from "../dist/sessions/pibo-data-store.js";
import {PrefixCapsuleStore} from "../dist/sessions/prefix-capsule.js";
import {SessionPrefixController} from "../dist/sessions/prefix-session.js";
import {createAgentRuntimeBindingPersistence} from "../dist/sessions/runtime-binding-persistence.js";
for(const Store of [SqlitePiboSessionStore,PiboDataSessionStore])test(`${Store.name}: prefix CLI inventories missing bindings and requires complete collection input`,async t=>{
 const root=await mkdtemp(join(tmpdir(),"pibo-prefix-cli-")),path=join(root,"sessions.sqlite"),capsules=new PrefixCapsuleStore(join(root,"prefixes"));
 const store=new Store(path);t.after(async()=>{store.close();await rm(root,{recursive:true,force:true});});
 const create=()=>store.create({channel:"test",kind:"chat",profile:"base"});
 const protectedSession=create(),legacy=create(),corrupt=create();create();
 store.updateRuntimeBinding(protectedSession.id,{...protectedSession.runtimeBinding,state:"bound"},{expectedRevision:1});
 let binding=store.get(protectedSession.id).runtimeBinding;
 const controller=new SessionPrefixController({store:capsules,getBinding:()=>binding,persistence:createAgentRuntimeBindingPersistence(store,{piboSessionId:protectedSession.id,onPersisted:next=>{binding=next;}})});
 const sealed=await controller.seal({codec:"fixture/v1",payload:"protected",nativeSessionId:protectedSession.piSessionId,evidence:"adapter-inputs",hasHistoricalModelInput:false});
 const orphan=await capsules.put("pi","fixture/v1","orphan");
 const db=new DatabaseSync(path),table=Store===SqlitePiboSessionStore?"pibo_session_runtime_bindings":"session_runtime_bindings";
 db.prepare(`DELETE FROM ${table} WHERE pibo_session_id=?`).run(legacy.id);
 db.prepare(`UPDATE ${table} SET metadata_json=? WHERE pibo_session_id=?`).run(JSON.stringify({piboSessionPrefixSettings:{reasoning:"secret-fixture",fastMode:"invalid"}}),corrupt.id);db.close();
 const cli=(...args)=>execFileSync(process.execPath,["dist/bin/pibo.js","debug","prefix",...args],{encoding:"utf8",stdio:["ignore","pipe","pipe"]});
 const report=JSON.parse(cli("inventory","--database",path,"--json"));
 assert.equal(report.total,4);assert.equal(report.counts.sealed,1);assert.equal(report.counts["legacy-unverified"],1);assert.equal(report.counts["recovery-required"],1);assert.equal(report.verification,"metadata-only");
 assert.ok(!JSON.stringify(report).includes("secret-fixture"));
 assert.throws(()=>cli("collect","--database",path,"--root",join(root,"prefixes"),"--apply"),/complete-inventory/);
 // Invalid unrelated metadata must prevent collection, even when a prefix reference is absent.
 assert.throws(()=>cli("collect","--database",path,"--root",join(root,"prefixes"),"--complete-inventory","--apply"));
 const repair=new DatabaseSync(path);repair.prepare(`UPDATE ${table} SET metadata_json='{}' WHERE pibo_session_id=?`).run(corrupt.id);repair.close();
 const common=["collect","--database",path,"--root",join(root,"prefixes"),"--complete-inventory","--json"];
 assert.equal(JSON.parse(cli(...common)).deleted,0);
 assert.equal(await readFile(join(root,"prefixes",orphan.digest+".capsule"),"utf8").then(()=>true),true);
 assert.equal(JSON.parse(cli(...common,"--apply")).deleted,1);
 assert.equal(await capsules.read(sealed.capsule,{adapterId:"pi",codec:"fixture/v1"}),"protected");
});
