import test from "node:test";
import assert from "node:assert/strict";
import {spawnSync} from "node:child_process";
import {mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {PiboDataStore} from "../dist/data/pibo-store.js";
import {MessageCommandStore} from "../dist/data/message-command-store.js";
import {inspectMessageQueue,reconcileMessageCommand} from "../dist/debug/message-queue.js";

function fixture(){
 const root=mkdtempSync(join(tmpdir(),"pibo-message-recovery-")),store=new PiboDataStore(join(root,"pibo.sqlite"),{payloadRootDir:join(root,"payloads")}),commands=new MessageCommandStore(store);let stream=0;
 const add=(key,state="accepted",delivery="queue")=>{const saved=store.transaction(()=>commands.insert({key,sessionId:"ps_test",roomId:"room",eventId:key,streamId:++stream,delivery,...commands.prepare({sessionId:"ps_test",roomId:"room",text:`body-${key}`,delivery})}));if(state!=="accepted")store.db.prepare("UPDATE message_commands SET state=?,error='fixture' WHERE id=?").run(state,saved.id);return commands.get(saved.id);};
 return {root,store,commands,add,close(){store.close();rmSync(root,{recursive:true,force:true});}};
}
function seedProjection(store,status){const now=new Date().toISOString();store.db.prepare("INSERT INTO sessions(id,channel,kind,profile,title,status,metadata_json,created_at,updated_at,last_activity_at) VALUES('ps_test','test','chat','base','Test',?,'{}',?,?,?)").run(status,now,now,now);store.db.prepare("INSERT INTO session_navigation(room_id,session_id,title,profile,status,last_activity_at,child_count,sort_key,updated_at) VALUES('room','ps_test','Test','base',?,?,0,?,?)").run(status,now,now,now);}


test("inspection and dry-run expose FIFO/evidence without mutation",()=>{const f=fixture();try{const first=f.add("one"),second=f.add("two");f.store.db.prepare("UPDATE message_commands SET state='interrupted',error='fixture' WHERE id=?").run(first.id);const before=f.commands.get(first.id);f.store.eventLog.appendEvent({sessionId:"ps_test",roomId:"room",topic:"pibo.output",type:"session_error",source:"test",eventId:"one",retentionClass:"audit_event"});const inspected=inspectMessageQueue(f.store,{sessionId:"ps_test"});assert.equal(inspected.commands[1].blockedBy,first.id);assert.deepEqual(inspected.commands[0].blocks,[second.id]);assert.equal(inspected.commands[0].terminalEvidence[0].type,"session_error");const dry=reconcileMessageCommand(f.store,{commandId:first.id,decision:"mark-failed",cancelSuccessors:true});assert.equal(dry.applied,false);assert.deepEqual(dry.successors.map(row=>row.id),[second.id]);assert.deepEqual(f.commands.get(first.id),before);assert.equal(f.commands.get(second.id).state,"accepted");assert.equal(Number(f.store.db.prepare("SELECT count(*) n FROM event_log WHERE type='durable_message_command.reconciled'").get().n),0);}finally{f.close();}});

test("apply is fenced, audited, idempotent, cancels selected successors, and never replays",()=>{const f=fixture();try{const first=f.add("one"),second=f.add("two"),third=f.add("three");f.store.db.prepare("UPDATE message_commands SET state='interrupted',error='fixture' WHERE id=?").run(first.id);const current=f.commands.get(first.id);const snapshot={state:current.state,token:f.store.db.prepare("SELECT token FROM message_commands WHERE id=?").get(first.id).token,updatedAt:current.updatedAt};const result=reconcileMessageCommand(f.store,{commandId:first.id,decision:"mark-failed",apply:true,cancelSuccessorIds:[second.id],expected:snapshot,actor:"test-operator"});assert.equal(result.applied,true);assert.equal(f.commands.get(first.id).state,"failed");assert.equal(f.commands.get(second.id).state,"failed");assert.equal(f.commands.get(third.id).state,"accepted");const audit=f.store.db.prepare("SELECT attributes_json,payload_ref FROM event_log WHERE type='durable_message_command.reconciled'").get();assert.equal(audit.payload_ref,null);const attributes=JSON.parse(audit.attributes_json);assert.equal(attributes.actor,"test-operator");assert.equal(attributes.replay,false);assert.deepEqual(attributes.affectedSuccessorIds,[second.id]);const repeated=reconcileMessageCommand(f.store,{commandId:first.id,decision:"mark-failed",apply:true});assert.equal(repeated.alreadyApplied,true);assert.equal(Number(f.store.db.prepare("SELECT count(*) n FROM event_log WHERE type='durable_message_command.reconciled'").get().n),1);}finally{f.close();}});

test("recovery refuses live leases, changed snapshots and ambiguous completion",()=>{const f=fixture();try{const first=f.add("one","interrupted");f.store.db.prepare("UPDATE message_commands SET owner='live',lease_until=? WHERE id=?").run(Date.now()+60000,first.id);assert.throws(()=>reconcileMessageCommand(f.store,{commandId:first.id,decision:"mark-failed",apply:true}),{code:"command_live_lease"});f.store.db.prepare("UPDATE message_commands SET owner=NULL,lease_until=0,updated_at=updated_at+1 WHERE id=?").run(first.id);assert.throws(()=>reconcileMessageCommand(f.store,{commandId:first.id,decision:"mark-failed",apply:true,expected:{state:"interrupted",token:0,updatedAt:first.updatedAt}}),{code:"command_snapshot_changed"});for(let i=0;i<8;i++)f.store.eventLog.appendEvent({sessionId:"ps_test",roomId:"room",topic:"pibo.output",type:"message_finished",source:"test",eventId:"one",retentionClass:"audit_event"});f.store.eventLog.appendEvent({sessionId:"ps_test",roomId:"room",topic:"pibo.output",type:"session_error",source:"test",eventId:"one",retentionClass:"audit_event"});assert.throws(()=>reconcileMessageCommand(f.store,{commandId:first.id,decision:"confirm-completed",apply:true}),/confirm-without-evidence/);const confirmed=reconcileMessageCommand(f.store,{commandId:first.id,decision:"confirm-completed",apply:true,confirmWithoutEvidence:first.id});assert.equal(confirmed.applied,true);assert.equal(f.commands.get(first.id).state,"completed");}finally{f.close();}});

test("selected successors with fresh ownership refuse dry-run and atomically refuse apply",()=>{const f=fixture();try{const first=f.add("one"),successor=f.add("two");f.store.db.prepare("UPDATE message_commands SET state='interrupted' WHERE id=?").run(first.id);f.store.db.prepare("UPDATE message_commands SET state='waiting_slot',owner='live-successor',lease_until=? WHERE id=?").run(Date.now()+60000,successor.id);for(const apply of [false,true])assert.throws(()=>reconcileMessageCommand(f.store,{commandId:first.id,decision:"mark-failed",cancelSuccessors:true,apply}),error=>error.code==="command_successor_live_lease"&&error.blockingCommandId===successor.id);assert.equal(f.commands.get(first.id).state,"interrupted");assert.equal(f.commands.get(successor.id).state,"waiting_slot");assert.equal(f.store.db.prepare("SELECT owner FROM message_commands WHERE id=?").get(successor.id).owner,"live-successor");assert.equal(Number(f.store.db.prepare("SELECT count(*) n FROM event_log WHERE type='durable_message_command.reconciled'").get().n),0);}finally{f.close();}});

test("historical receipt recovery does not overwrite newer completed or live Session projection",()=>{for(const scenario of ["completed","live-steer"]){const f=fixture();try{seedProjection(f.store,scenario==="completed"?"idle":"running");const first=f.add("old"),newer=f.add("new",undefined,scenario==="live-steer"?"steer":"queue");f.store.db.prepare("UPDATE message_commands SET state='interrupted' WHERE id=?").run(first.id);if(scenario==="completed")f.commands.recordOutput("ps_test","new","message_finished");else f.store.db.prepare("UPDATE message_commands SET state='running',owner='live',lease_until=? WHERE id=?").run(Date.now()+60000,newer.id);reconcileMessageCommand(f.store,{commandId:first.id,decision:"mark-failed",apply:true});const projection=f.store.db.prepare("SELECT s.status session_status,n.status navigation_status FROM sessions s JOIN session_navigation n ON n.session_id=s.id WHERE s.id='ps_test'").get();assert.equal(projection.session_status,scenario==="completed"?"idle":"running");assert.equal(projection.navigation_status,projection.session_status);}finally{f.close();}}});

test("inspection prioritizes active barriers over deep terminal history and exposes bounded pages",()=>{const f=fixture();try{const terminal=[];for(let i=0;i<205;i++){const row=f.add(`done-${i}`);terminal.push(row);f.commands.recordOutput("ps_test",row.eventId,"message_finished");}const blocker=f.add("blocker"),successor=f.add("successor");f.store.db.prepare("UPDATE message_commands SET state='interrupted' WHERE id=?").run(blocker.id);const inspected=inspectMessageQueue(f.store,{sessionId:"ps_test"});assert.equal(inspected.commands.length,22);const shownBlocker=inspected.commands.find(row=>row.id===blocker.id),shownSuccessor=inspected.commands.find(row=>row.id===successor.id);assert.equal(shownBlocker.context,"active");assert.equal(shownBlocker.previousCommandId,terminal.at(-1).id);assert.equal(shownBlocker.nextCommandId,successor.id);assert.deepEqual(shownBlocker.blocks,[successor.id]);assert.equal(shownSuccessor.blockedBy,blocker.id);assert.equal(inspected.pagination.active.truncated,false);assert.equal(inspected.pagination.terminalContext.truncated,true);const older=inspectMessageQueue(f.store,{sessionId:"ps_test",beforeTerminalStreamId:inspected.pagination.terminalContext.nextBeforeStreamId});assert.equal(older.commands.some(row=>row.id===terminal.at(-1).id),false);assert.equal(older.commands.some(row=>row.id===blocker.id),true,"active context remains visible while paging terminal history");}finally{f.close();}});

test("authoritative completion needs no override and partial failure rolls back",()=>{const f=fixture();try{const first=f.add("one"),second=f.add("two");f.store.db.prepare("UPDATE message_commands SET state='interrupted',error='fixture' WHERE id=?").run(first.id);f.store.eventLog.appendEvent({sessionId:"ps_test",roomId:"room",topic:"pibo.output",type:"message_finished",source:"test",eventId:"one",retentionClass:"audit_event"});const complete=reconcileMessageCommand(f.store,{commandId:first.id,decision:"confirm-completed",apply:true});assert.equal(complete.applied,true);assert.equal(f.commands.get(first.id).state,"completed");f.store.db.prepare("UPDATE message_commands SET state='interrupted' WHERE id=?").run(first.id);assert.throws(()=>reconcileMessageCommand(f.store,{commandId:first.id,decision:"mark-failed",apply:true,cancelSuccessors:true,beforeAudit(){throw new Error("injected audit failure");}}),/injected/);assert.equal(f.commands.get(first.id).state,"interrupted");assert.equal(f.commands.get(second.id).state,"accepted");}finally{f.close();}});

test("real CLI performs temporary-store inspection, dry-run and apply",()=>{const f=fixture();try{const first=f.add("one"),second=f.add("two");f.store.db.prepare("UPDATE message_commands SET state='interrupted',error='fixture' WHERE id=?").run(first.id);const run=args=>spawnSync(process.execPath,["dist/bin/pibo.js","debug","message-queue",...args],{cwd:process.cwd(),encoding:"utf8",env:{...process.env,PIBO_HOME:f.root}});const inspect=run(["inspect","--session","ps_test","--json"]);assert.equal(inspect.status,0,inspect.stderr);assert.equal(JSON.parse(inspect.stdout).commands[0].id,first.id);const paged=run(["inspect","--session","ps_test","--after-stream",String(first.streamId),"--json"]);assert.equal(paged.status,0,paged.stderr);assert.equal(JSON.parse(paged.stdout).commands.some(row=>row.id===second.id),true);const dry=run(["reconcile",first.id,"--mark-failed","--cancel-successors","--json"]);assert.equal(dry.status,0,dry.stderr);assert.equal(JSON.parse(dry.stdout).applied,false);assert.equal(f.commands.get(first.id).state,"interrupted");const apply=run(["reconcile",first.id,"--mark-failed","--cancel-successors","--apply","--json"]);assert.equal(apply.status,0,apply.stderr);assert.equal(JSON.parse(apply.stdout).applied,true);assert.equal(f.commands.get(first.id).state,"failed");assert.equal(f.commands.get(second.id).state,"failed");const replay=run(["reconcile",first.id,"--replay","--apply"]);assert.notEqual(replay.status,0);assert.match(replay.stderr,/Replay is unsupported/);}finally{f.close();}});
