import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtemp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { SqlitePiboSessionStore } from '../dist/sessions/sqlite-store.js';
import { PiboDataSessionStore } from '../dist/sessions/pibo-data-store.js';
import { PrefixCapsuleStore } from '../dist/sessions/prefix-capsule.js';
import { SessionPrefixController } from '../dist/sessions/prefix-session.js';
import { createAgentRuntimeBindingPersistence } from '../dist/sessions/runtime-binding-persistence.js';
for (const Store of [SqlitePiboSessionStore,PiboDataSessionStore]) test(`${Store.name}: explicit model authorization survives restart and can be aborted without replacing the original prefix`,async t=>{
 const root=await mkdtemp(join(tmpdir(),'pibo-prefix-rebaseline-'));
 const sessions=new Store(join(root,'sessions.sqlite'));
 t.after(async()=>{sessions.close();await rm(root,{recursive:true,force:true});});
 const session=sessions.create({channel:'test',kind:'chat',profile:'base'});
 sessions.updateRuntimeBinding(session.id,{...session.runtimeBinding,state:'bound'},{expectedRevision:1});
 const make=()=>{let binding=sessions.get(session.id).runtimeBinding;return new SessionPrefixController({store:new PrefixCapsuleStore(join(root,'prefixes')),getBinding:()=>binding,persistence:createAgentRuntimeBindingPersistence(sessions,{piboSessionId:session.id,onPersisted:next=>{binding=next;}})});};
 const controller=make(),oldModel={provider:'fixture',id:'old'},nextModel={provider:'fixture',id:'new'};
 const prefix=await controller.seal({codec:'fixture/v1',payload:'original prefix',nativeSessionId:session.piSessionId,evidence:'adapter-inputs',hasHistoricalModelInput:false});
 assert.equal(await controller.beginModelChange(oldModel,oldModel),undefined);
 const pending=await controller.beginModelChange(oldModel,nextModel);
 const cold=make();assert.equal(cold.rebaseline.id,pending.id);assert.deepEqual(cold.binding,prefix);
 await assert.rejects(cold.beginCompaction(null),/explicit prefix transition/);
 await assert.rejects(cold.beginModelChange(oldModel,nextModel),/pending/);
 const current=sessions.get(session.id).runtimeBinding;
 assert.throws(()=>sessions.updateRuntimeBinding(session.id,{...current,metadata:{...current.metadata,piboSessionPrefixRebaseline:{...current.metadata.piboSessionPrefixRebaseline,targetModel:{provider:'fixture',id:'unauthorized'}}}},{expectedRevision:current.revision}),/cannot be replaced/);
 await assert.rejects(cold.abortModelChange('wrong-id'),/no longer pending/);
 await cold.abortModelChange(pending.id);
 assert.equal(make().rebaseline,undefined);assert.deepEqual(make().binding,prefix);
 assert.equal(await make().restore('fixture/v1'),'original prefix');
 const restarted=make(),second=await restarted.beginModelChange(oldModel,nextModel);
 const replacement={codec:'fixture/v1',payload:'new model prefix',nativeSessionId:session.piSessionId,evidence:'adapter-inputs',hasHistoricalModelInput:true};
 await assert.rejects(restarted.seal(replacement),/dispatch authorization/);
 const replaced=await restarted.seal({...replacement,rebaselineId:second.id});
 assert.equal(replaced.epoch,prefix.epoch+1);assert.equal(replaced.reason,'model-change');
 assert.notEqual(replaced.capsule.digest,prefix.capsule.digest);
 assert.equal(make().rebaseline,undefined);assert.equal(await make().restore('fixture/v1'),'new model prefix');
 await assert.rejects(make().abortModelChange(second.id),/no longer pending/);

});
