import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtemp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { SqlitePiboSessionStore } from '../dist/sessions/sqlite-store.js';
import { PiboDataSessionStore } from '../dist/sessions/pibo-data-store.js';
import { PrefixCapsuleStore } from '../dist/sessions/prefix-capsule.js';
import { SessionPrefixController } from '../dist/sessions/prefix-session.js';
import { createAgentRuntimeBindingPersistence } from '../dist/sessions/runtime-binding-persistence.js';
import { preparePrefixRuntimeTransition } from '../dist/sessions/prefix-rebaseline.js';
for (const Store of [SqlitePiboSessionStore,PiboDataSessionStore]) test(`${Store.name}: explicit model authorization survives restart and can be aborted without replacing the original prefix`,async t=>{
 const root=await mkdtemp(join(tmpdir(),'pibo-prefix-rebaseline-'));
 const sessions=new Store(join(root,'sessions.sqlite'));
 t.after(async()=>{sessions.close();await rm(root,{recursive:true,force:true});});
 const session=sessions.create({channel:'test',kind:'chat',profile:'base'});
 sessions.updateRuntimeBinding(session.id,{...session.runtimeBinding,state:'bound'},{expectedRevision:1});
 const make=()=>{let binding=sessions.get(session.id).runtimeBinding;return new SessionPrefixController({store:new PrefixCapsuleStore(join(root,'prefixes')),getBinding:()=>binding,persistence:createAgentRuntimeBindingPersistence(sessions,{piboSessionId:session.id,onPersisted:next=>{binding=next;}})});};
 const controller=make(),oldModel={provider:'fixture',id:'old'},nextModel={provider:'fixture',id:'new'};
 await controller.sealResources(async()=>({format:1,context:[{id:'old',label:'Old context',required:true,order:0,content:'older resource'}],skills:[],files:[]}));
 const prefix=await controller.seal({codec:'fixture/v1',payload:'original prefix',nativeSessionId:session.piSessionId,evidence:'adapter-inputs',hasHistoricalModelInput:false});
 assert.equal(await controller.beginModelChange(oldModel,oldModel),undefined);
 const pending=await controller.beginModelChange(oldModel,nextModel);
 const cold=make();assert.equal(cold.rebaseline.id,pending.id);assert.deepEqual(cold.binding,prefix);
 await assert.rejects(cold.beginCompaction(null),/explicit prefix transition/);
 await assert.rejects(cold.beginModelChange(oldModel,nextModel),/pending/);
 const current=sessions.get(session.id).runtimeBinding;
 assert.throws(()=>sessions.updateRuntimeBinding(session.id,{...current,metadata:{...current.metadata,piboSessionPrefixRebaseline:{...current.metadata.piboSessionPrefixRebaseline,targetModel:{provider:'fixture',id:'unauthorized'}}}},{expectedRevision:current.revision}),/cannot be replaced/);
 await assert.rejects(cold.abortModelChange('wrong-id'),/no longer pending/);
 await cold.abortModelChange(pending.id);
 assert.equal(make().rebaseline,undefined);assert.deepEqual(make().binding,prefix);
 assert.equal(await make().restore('fixture/v1'),'original prefix');
 const restarted=make(),second=await restarted.beginModelChange(oldModel,nextModel);
 const replacement={codec:'fixture/v1',payload:'new model prefix',nativeSessionId:session.piSessionId,evidence:'adapter-inputs',hasHistoricalModelInput:true};
 await assert.rejects(restarted.seal(replacement),/dispatch authorization/);
 const replaced=await restarted.seal({...replacement,rebaselineId:second.id});
 assert.equal(replaced.epoch,prefix.epoch+1);assert.equal(replaced.reason,'model-change');
 assert.notEqual(replaced.capsule.digest,prefix.capsule.digest);
 assert.equal(make().rebaseline,undefined);assert.equal(await make().restore('fixture/v1'),'new model prefix');
 await assert.rejects(make().abortModelChange(second.id),/no longer pending/);

 const source=sessions.get(session.id).runtimeBinding;
 const target={...source,runtimeInstanceId:'omp-native',adapterId:'orp',state:'unbound',nativeSessionId:undefined,locator:undefined,metadata:{}};
 const beginRuntime=()=>{const current=sessions.get(session.id).runtimeBinding;return sessions.updateRuntimeBinding(session.id,preparePrefixRuntimeTransition(current,target,nextModel),{expectedRevision:current.revision,mode:'rebind'});};
 const runtimePending=beginRuntime();
 assert.equal(make().binding,undefined);assert.equal(make().rebaseline.reason,'runtime-change');
 assert.equal(await make().restore('omp-fixture/v1'),undefined);
 assert.equal(make().rebaseline.sourceBinding.metadata.piboSessionPrefix.capsule.digest,replaced.capsule.digest);
 assert.throws(()=>sessions.updateRuntimeBinding(session.id,{...runtimePending,metadata:{}},{expectedRevision:runtimePending.revision}),/next epoch/);
 const restored=sessions.updateRuntimeBinding(session.id,source,{expectedRevision:runtimePending.revision,mode:'rebind'});
 assert.deepEqual(restored.metadata.piboSessionPrefix,replaced);
 const another=beginRuntime();
 sessions.updateRuntimeBinding(session.id,{...another,state:'bound',nativeSessionId:'target-native'},{expectedRevision:another.revision});
 const native=make();
 await native.sealResources(async()=>({format:1,context:[{id:'imported',label:'Context',required:true,order:0,content:'resource before refresh'}],skills:[],files:[]}));
 const completed=await native.seal({codec:'omp-fixture/v1',payload:'new runtime prefix',nativeSessionId:'target-native',evidence:'adapter-inputs',hasHistoricalModelInput:true,rebaselineId:native.rebaseline.id});
 assert.equal(completed.epoch,replaced.epoch+1);assert.equal(completed.reason,'runtime-change');
 assert.equal(make().rebaseline,undefined);
 assert.throws(()=>sessions.updateRuntimeBinding(session.id,source,{expectedRevision:sessions.get(session.id).runtimeBinding.revision,mode:'rebind'}),/epoch|frozen resources/);

 const refreshSource=sessions.get(session.id).runtimeBinding;
 const refreshTarget={...refreshSource,nativeSessionId:'full-history-copy',metadata:{}};
 let refreshing=sessions.updateRuntimeBinding(session.id,preparePrefixRuntimeTransition(refreshSource,refreshTarget,nextModel,'explicit-refresh'),{expectedRevision:refreshSource.revision,mode:'rebind'});
 assert.equal(make().rebaseline.reason,'explicit-refresh');
 assert.deepEqual(refreshing.metadata.piboSessionPrefixResourceDependencies,[refreshSource.metadata.piboSessionPrefixResources]);
 const tampered={...refreshing,metadata:{...refreshing.metadata,piboSessionPrefixResourceDependencies:[]}};
 assert.throws(()=>sessions.updateRuntimeBinding(session.id,tampered,{expectedRevision:refreshing.revision}),/historical resource/);
 const cancelledRefresh=sessions.updateRuntimeBinding(session.id,refreshSource,{expectedRevision:refreshing.revision,mode:'rebind'});
 assert.deepEqual(cancelledRefresh.metadata,refreshSource.metadata);
 refreshing=sessions.updateRuntimeBinding(session.id,preparePrefixRuntimeTransition(cancelledRefresh,refreshTarget,nextModel,'explicit-refresh'),{expectedRevision:cancelledRefresh.revision,mode:'rebind'});
 const refreshController=make();
 const newBase=await refreshController.seal({codec:'omp-fixture/v1',payload:'refreshed current base',nativeSessionId:'full-history-copy',evidence:'adapter-inputs',hasHistoricalModelInput:true,rebaselineId:refreshController.rebaseline.id});
 await rm(join(root,'prefixes','resources'),{recursive:true,force:true});
 await make().restoreResources();
 const dependency=sessions.get(session.id).runtimeBinding.metadata.piboSessionPrefixResourceDependencies[0];
 await rm(join(root,'prefixes',dependency.digest+'.capsule'));
 await assert.rejects(make().restoreResources(),/recovery required/);
 assert.equal(newBase.reason,'explicit-refresh');assert.equal(newBase.epoch,completed.epoch+1);

});
