import assert from "node:assert/strict";
import {test} from "node:test";
import {mkdtemp,rm} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {SqlitePiboSessionStore} from "../dist/sessions/sqlite-store.js";
import {PiboDataSessionStore} from "../dist/sessions/pibo-data-store.js";
import {PrefixCapsuleStore} from "../dist/sessions/prefix-capsule.js";
import {SessionPrefixController} from "../dist/sessions/prefix-session.js";
import {createAgentRuntimeBindingPersistence} from "../dist/sessions/runtime-binding-persistence.js";

for(const Store of [SqlitePiboSessionStore,PiboDataSessionStore])test(`${Store.name}: settings changes persist before native mutation, restore cold and roll back both controls`,async t=>{
 const root=await mkdtemp(join(tmpdir(),"pibo-prefix-settings-"));
 const sessions=new Store(join(root,"sessions.sqlite"));
 t.after(async()=>{sessions.close();await rm(root,{recursive:true,force:true});});
 const session=sessions.create({channel:"test",kind:"chat",profile:"base"});
 sessions.updateRuntimeBinding(session.id,{...session.runtimeBinding,state:"bound"},{expectedRevision:1});
 const make=()=>{let binding=sessions.get(session.id).runtimeBinding;return new SessionPrefixController({store:new PrefixCapsuleStore(join(root,"prefixes")),getBinding:()=>binding,persistence:createAgentRuntimeBindingPersistence(sessions,{piboSessionId:session.id,onPersisted:next=>{binding=next;}})});};
 const model={provider:"fixture",id:"model"},previous={reasoning:"low",fastMode:false},target={reasoning:"high",fastMode:true};
 let native=structuredClone(previous),controller=make();
 const input={codec:"fixture/v1",payload:"original prefix",nativeSessionId:session.piSessionId,evidence:"adapter-inputs",hasHistoricalModelInput:false};
 const original=await controller.seal(input);
 const apply=async value=>{assert.equal(make().rebaseline.reason,"settings-change","native mutation requires durable authorization");native=structuredClone(value);return native;};
 await controller.changeSettings(model,previous,target,apply);
 assert.deepEqual(make().configuredSettings,target);assert.deepEqual(make().binding,original);
 controller=make();
 await controller.changeSettings(model,target,previous,apply);
 assert.equal(make().rebaseline,undefined);assert.deepEqual(native,previous);assert.deepEqual(make().binding,original);
 controller=make();
 let attempts=0;
 await assert.rejects(controller.changeSettings(model,previous,target,async value=>{await apply(value);if(++attempts===1)throw new Error("native rejected after partial mutation");return native;}),/native rejected/);
 assert.deepEqual(native,previous);assert.equal(make().rebaseline,undefined);
 controller=make();await controller.changeSettings(model,previous,target,apply);
 controller=make();
 await assert.rejects(controller.seal({...input,payload:"new settings prefix",hasHistoricalModelInput:true}),/authorization/);
 await controller.seal({...input,payload:"new settings prefix",hasHistoricalModelInput:true,rebaselineId:controller.rebaseline.id});
 assert.deepEqual(make().configuredSettings,target);assert.equal(make().binding.reason,"settings-change");assert.equal(make().binding.epoch,original.epoch+1);
 const binding=sessions.get(session.id).runtimeBinding;
 assert.throws(()=>sessions.updateRuntimeBinding(session.id,{...binding,metadata:{...binding.metadata,piboSessionPrefixSettings:previous}},{expectedRevision:binding.revision}),/explicit completed transition/);
 controller=make();await controller.changeSettings(model,target,target,async value=>value);
 assert.equal(make().rebaseline,undefined);
 assert.equal(make().binding.epoch,original.epoch+1);
 const nextModel={provider:"fixture",id:"second"};
 native=structuredClone(target);
 const restore=async settings=>{native=structuredClone(settings);};
 await controller.changeModel(model,nextModel,async selected=>{native={reasoning:"low",fastMode:false};return selected;},{previous:target,current:()=>native,restore});
 controller=make();
 assert.deepEqual(controller.rebaseline.previousSettings,target);
 assert.deepEqual(controller.configuredSettings,{reasoning:"low",fastMode:false},"cold pending model restores its actual controls");
 await controller.changeModel(nextModel,model,async selected=>selected,{previous:previous,restore});
 assert.deepEqual(native,target,"cold model cancellation restores both controls, not just the selected model");
 assert.equal(make().rebaseline,undefined);
 controller=make();
 await controller.changeModel(model,nextModel,async selected=>{native={reasoning:"medium",fastMode:false};return selected;},{previous:target,current:()=>native,restore});
 controller=make();await controller.seal({...input,payload:"model with confirmed controls",hasHistoricalModelInput:true,rebaselineId:controller.rebaseline.id});
 assert.deepEqual(make().configuredSettings,native,"completed model changes retain their control checkpoint");
});
