export type NumberStats = {
	count: number;
	min?: number;
	p50?: number;
	p90?: number;
	p99?: number;
	max?: number;
	avg?: number;
};

export type StreamingDebugCounters = Record<string, unknown> & {
	startedAt?: string;
	eventCount?: number;
	textDeltaCount?: number;
	textDeltaBytes?: number;
	reasoningDeltaCount?: number;
	reasoningDeltaBytes?: number;
	enqueueCount?: number;
	flushCount?: number;
	flushedEventCount?: number;
	overlayUpdateCount?: number;
	overlayEventCount?: number;
	liveTraceComputeCount?: number;
	liveTraceComputeDurationMsTotal?: number;
	liveTraceComputeDurationMsMax?: number;
	markdownRenderCount?: number;
	markdownRenderPlainCount?: number;
	markdownRenderFullCount?: number;
	markdownRenderCommonMarkCount?: number;
	markdownRenderGfmCount?: number;
	markdownRenderGfmFastCount?: number;
	markdownRenderDurationMsTotal?: number;
	markdownRenderDurationMsMax?: number;
	markdownRenderPlainDurationMsMax?: number;
	markdownRenderFullDurationMsMax?: number;
	markdownRenderCommonMarkDurationMsMax?: number;
	markdownRenderGfmDurationMsMax?: number;
	markdownRenderGfmFastDurationMsMax?: number;
	traceRefreshCompletedCount?: number;
	traceRefreshFailedCount?: number;
	currentOutputLength?: number;
	traceBaseOutputLength?: number;
	firstEventAt?: string;
	firstTextDeltaAt?: string;
	firstReasoningDeltaAt?: string;
	firstEnqueueAt?: string;
	firstFlushAt?: string;
	firstOverlayUpdateAt?: string;
	lastDurableCursor?: string;
	lastTransientLiveId?: string;
};

export type StreamingSmoothnessScore = {
	smoothness: number;
	domGapP50Ms?: number;
	domGapP90Ms?: number;
	domJumpP90Chars?: number;
	textDeltaCount: number;
	domPositiveUpdateCount: number;
	firstVisibleMs?: number;
};

export type StreamingBenchmarkProviderTelemetry = {
	requested: boolean;
	available: boolean;
	providerRequestId: string;
	piboSessionId?: string;
	turnId?: string;
	provider?: string;
	api?: string;
	model?: string;
	transport?: string;
	status?: string;
	startedAt?: string;
	completedAt?: string;
	httpStatus?: number;
	upstreamResponseId?: string;
	rawEventCount?: number;
	normalizedEventCount?: number;
	parseErrorCount?: number;
	unknownEventCount?: number;
	firstByteLatencyMs?: number;
	firstTextLatencyMs?: number;
	firstReasoningLatencyMs?: number;
	eventTypeCounts?: Record<string, unknown>;
	textDeltaCount: number;
	reasoningDeltaCount: number;
	textDeltaBytes: NumberStats;
	reasoningDeltaBytes: NumberStats;
	textDeltaGapsMs: NumberStats;
	reasoningDeltaGapsMs: NumberStats;
	eventPageCount: number;
	truncated: boolean;
	error?: string;
};

export type StreamingBenchmarkCadence = {
	fixtureScheduleGapP90Ms: number;
	domGapP90Ms?: number;
	sseTextGapP90Ms?: number;
	domLagOverScheduleP90Ms?: number;
	sseTextLagOverScheduleP90Ms?: number;
	domToScheduleP90Ratio?: number;
	sseTextToScheduleP90Ratio?: number;
};

export type StreamingBenchmarkProviderPreservation = {
	providerTextDeltaCount: number;
	providerReasoningDeltaCount: number;
	sseTextEventCount?: number;
	sseReasoningEventCount?: number;
	selectedLiveTextEventCountAfterStart?: number;
	selectedLiveReasoningEventCountAfterStart?: number;
	domPositiveUpdateCount?: number;
	sseTextToProviderRatio?: number;
	sseReasoningToProviderRatio?: number;
	selectedLiveTextToProviderRatio?: number;
	selectedLiveReasoningToProviderRatio?: number;
	domPositiveToProviderTextRatio?: number;
};

export type StreamingBenchmarkLivePipeline = {
	expectedSource: "fixture" | "provider" | "debug";
	expectedTextDeltaCount: number;
	expectedReasoningDeltaCount: number;
	expectedInputEventCount: number;
	expectedPipelineEventCount?: number;
	enqueueCount?: number;
	flushCount?: number;
	flushedEventCount?: number;
	overlayUpdateCount?: number;
	overlayEventCount?: number;
	currentOutputLength?: number;
	expectedTextBytes?: number;
	enqueueToExpectedRatio?: number;
	flushedEventsToExpectedRatio?: number;
	overlayEventsToExpectedRatio?: number;
	currentOutputToExpectedTextBytesRatio?: number;
	flushToEnqueueRatio?: number;
	overlayUpdatesToFlushedEventsRatio?: number;
	firstEventMs?: number;
	firstTextDeltaMs?: number;
	firstReasoningDeltaMs?: number;
	firstEnqueueMs?: number;
	firstFlushMs?: number;
	firstOverlayUpdateMs?: number;
};

export type StreamingBenchmarkEventSourceStreamProbe = {
	url: string;
	mode?: string;
	role: "selected-live" | "room-summary" | "chat-events";
	piboSessionId?: string;
	roomId?: string;
	sinceValues: string[];
	liveSinceValues?: string[];
	openCountAfterStart: number;
	errorCountAfterStart: number;
	closeCountAfterStart: number;
	forcedCloseCountAfterStart: number;
	eventCount: number;
	eventCountAfterStart: number;
	textEventCount: number;
	textEventCountAfterStart: number;
	reasoningEventCount: number;
	reasoningEventCountAfterStart: number;
	transientIdCount: number;
	uniqueTransientIdCount: number;
	transientIdCountAfterStart: number;
	uniqueTransientIdCountAfterStart: number;
	durableIdCount: number;
	otherIdCount: number;
	liveReplayEventCount?: number;
	liveReplayEventCountAfterStart?: number;
	liveReplayMissedCount?: number;
	liveReplayMissedCountAfterStart?: number;
	liveReplayDuplicateCount?: number;
	liveReplayDuplicateCountAfterStart?: number;
	liveReplayEvictedBeforeMax?: number;
	liveReplayCursorLagMax?: number;
	liveReplayCursorLagMaxAfterStart?: number;
	lastEventId?: string;
	firstEventMsAfterStart?: number;
	firstTextEventMsAfterStart?: number;
	firstReasoningEventMsAfterStart?: number;
};

export type StreamingBenchmarkEventSourceProbe = {
	requested: boolean;
	installed: boolean;
	forcedReconnectAtMs?: number;
	openCount: number;
	openCountAfterStart: number;
	errorCount: number;
	errorCountAfterStart: number;
	closeCount: number;
	forcedCloseCount: number;
	forcedCloseCountAfterStart: number;
	eventCount: number;
	eventCountAfterStart: number;
	textEventCount: number;
	textEventCountAfterStart: number;
	reasoningEventCount: number;
	reasoningEventCountAfterStart: number;
	transientIdCount: number;
	uniqueTransientIdCount: number;
	transientIdCountAfterStart: number;
	uniqueTransientIdCountAfterStart: number;
	durableIdCount: number;
	otherIdCount: number;
	lastEventId?: string;
	firstTransientId?: string;
	lastTransientId?: string;
	firstEventMsAfterStart?: number;
	firstTextEventMsAfterStart?: number;
	firstReasoningEventMsAfterStart?: number;
	transientIdResetObserved: boolean;
	reconnectObserved: boolean;
	textDropRequested: boolean;
	textDropDurationMs?: number;
	textDropCount: number;
	textDropTextEventCount: number;
	streams: StreamingBenchmarkEventSourceStreamProbe[];
};

export type StreamingBenchmarkSseProbe = {
	requested: boolean;
	installed: boolean;
	url?: string;
	status?: number;
	headers: Record<string, string>;
	aborted: boolean;
	errors: string[];
	chunkCount: number;
	chunkBytes: NumberStats;
	chunkGapsMs: NumberStats;
	textEventsPerChunk: NumberStats;
	eventCount: number;
	textEventCount: number;
	reasoningEventCount: number;
	textDeltaBytes: NumberStats;
	textEventGapsMs: NumberStats;
	idCount: number;
	transientIdCount: number;
	durableIdCount: number;
	otherIdCount: number;
	lastEventId?: string;
	firstChunkMs?: number;
	firstEventMs?: number;
	firstTextEventMs?: number;
	firstReasoningEventMs?: number;
};

export type StreamingBenchmarkTraceProbeSample = {
	t: number;
	version?: string;
	eventCount?: number;
	rawEventCount: number;
	assistantOutputLength: number;
	liveVersion: boolean;
	rawEventTypes: Record<string, number>;
};

export type StreamingBenchmarkTraceProbe = {
	requested: boolean;
	installed: boolean;
	piboSessionId?: string;
	intervalMs: number;
	sampleCount: number;
	fetchCount: number;
	failedFetchCount: number;
	liveVersionCount: number;
	firstLiveVersionMs?: number;
	durableEventCountStart?: number;
	durableEventCountEnd?: number;
	maxAssistantOutputLength: number;
	finalAssistantOutputLength?: number;
	samples: StreamingBenchmarkTraceProbeSample[];
};

export type StreamingBenchmarkOverlayDrop = {
	requested: boolean;
	installed: boolean;
	dropTypes: string[];
	droppedCount: number;
	passedCount: number;
	lastDroppedType?: string;
};

export type StreamingBenchmark = {
	kind: "streaming-benchmark";
	createdAt: string;
	url: string;
	title: string;
	durationMs: number;
	debug: {
		enabledRequested: boolean;
		available: boolean;
		reset: boolean;
		before?: StreamingDebugCounters;
		stateBeforeReset?: StreamingDebugCounters;
		after?: StreamingDebugCounters;
		delta?: Record<string, number>;
	};
	dom: {
		selector: string;
		targetCountStart: number;
		targetCountEnd: number;
		lengthStart: number;
		lengthEnd: number;
		lengthMax: number;
		updateCount: number;
		positiveUpdateCount: number;
		firstPositiveUpdateMs?: number;
		lastPositiveUpdateMs?: number;
		gapsMs: NumberStats;
		positiveCharJumps: NumberStats;
	};
	raf: { count: number; gapsMs: NumberStats };
	longTasks: { count: number; totalMs: number; maxMs: number };
	fixture?: { requested: boolean; mode: "browser" | "backend"; profile?: string; mix?: string; simulation?: "reconnect" | "trace-catchup" | "overlay-drop"; available: boolean; started: boolean; deltaCount?: number; reasoningDeltaCount?: number; cadenceMs?: number; scheduleMs?: number[]; scheduleGapsMs?: NumberStats; reasoningScheduleMs?: number[]; reasoningScheduleGapsMs?: NumberStats; textBytes?: number; reasoningBytes?: number; preludeMessages?: number; piboSessionId?: string; error?: string };
	eventSource?: StreamingBenchmarkEventSourceProbe;
	sse?: StreamingBenchmarkSseProbe;
	trace?: StreamingBenchmarkTraceProbe;
	overlayDrop?: StreamingBenchmarkOverlayDrop;
	provider?: StreamingBenchmarkProviderTelemetry;
	cadence?: StreamingBenchmarkCadence;
	livePipeline?: StreamingBenchmarkLivePipeline;
	providerPreservation?: StreamingBenchmarkProviderPreservation;
	negativeProfile?: StreamingNegativeProfile;
	score: StreamingSmoothnessScore;
	regressions: string[];
	warnings: string[];
	assertion?: StreamingBenchmarkAssertion;
};

export type StreamingBenchmarkSummary = {
	runs: number;
	smoothness: NumberStats;
	textDeltaCount: NumberStats;
	reasoningDeltaCount: NumberStats;
	domPositiveUpdateCount: NumberStats;
	domGapP50Ms: NumberStats;
	domGapP90Ms: NumberStats;
	domGapMaxMs: NumberStats;
	domJumpP90Chars: NumberStats;
	domJumpMaxChars: NumberStats;
	firstVisibleMs: NumberStats;
	longTaskMaxMs: NumberStats;
	regressionCount: NumberStats;
	debugEnqueueCount: NumberStats;
	debugFlushCount: NumberStats;
	debugFlushedEventCount: NumberStats;
	debugOverlayUpdateCount: NumberStats;
	debugOverlayEventCount: NumberStats;
	debugLiveTraceComputeCount: NumberStats;
	debugLiveTraceComputeDurationTotalMs: NumberStats;
	debugLiveTraceComputeDurationMaxMs: NumberStats;
	debugMarkdownRenderCount: NumberStats;
	debugMarkdownRenderPlainCount: NumberStats;
	debugMarkdownRenderFullCount: NumberStats;
	debugMarkdownRenderCommonMarkCount: NumberStats;
	debugMarkdownRenderGfmCount: NumberStats;
	debugMarkdownRenderGfmFastCount: NumberStats;
	debugMarkdownRenderDurationTotalMs: NumberStats;
	debugMarkdownRenderDurationMaxMs: NumberStats;
	debugMarkdownRenderPlainDurationMaxMs: NumberStats;
	debugMarkdownRenderFullDurationMaxMs: NumberStats;
	debugMarkdownRenderCommonMarkDurationMaxMs: NumberStats;
	debugMarkdownRenderGfmDurationMaxMs: NumberStats;
	debugMarkdownRenderGfmFastDurationMaxMs: NumberStats;
	debugTraceRefreshScheduledCount: NumberStats;
	debugTraceRefreshCompletedCount: NumberStats;
	debugTraceRefreshFailedCount: NumberStats;
	debugTraceRefreshDurationMaxMs: NumberStats;
	debugCurrentOutputLength: NumberStats;
	debugTraceBaseOutputLength: NumberStats;
	liveExpectedInputEventCount: NumberStats;
	liveExpectedPipelineEventCount: NumberStats;
	liveEnqueueToExpectedRatio: NumberStats;
	liveFlushedEventsToExpectedRatio: NumberStats;
	liveOverlayEventsToExpectedRatio: NumberStats;
	liveCurrentOutputToExpectedTextBytesRatio: NumberStats;
	liveFlushToEnqueueRatio: NumberStats;
	liveOverlayUpdatesToFlushedEventsRatio: NumberStats;
	liveFirstEventMs: NumberStats;
	liveFirstTextDeltaMs: NumberStats;
	liveFirstReasoningDeltaMs: NumberStats;
	liveFirstEnqueueMs: NumberStats;
	liveFirstFlushMs: NumberStats;
	liveFirstOverlayUpdateMs: NumberStats;
	traceSampleCount: NumberStats;
	traceLiveVersionCount: NumberStats;
	traceFirstLiveVersionMs: NumberStats;
	traceMaxAssistantOutputLength: NumberStats;
	traceFinalAssistantOutputLength: NumberStats;
	traceDurableEventDelta: NumberStats;
	fixtureScheduleGapP90Ms: NumberStats;
	domLagOverFixtureScheduleP90Ms: NumberStats;
	sseTextLagOverFixtureScheduleP90Ms: NumberStats;
	domToFixtureScheduleP90Ratio: NumberStats;
	sseTextToFixtureScheduleP90Ratio: NumberStats;
	eventSourceTextEventCountAfterStart: NumberStats;
	eventSourceReasoningEventCountAfterStart: NumberStats;
	eventSourceForcedCloseCountAfterStart: NumberStats;
	eventSourceReconnectOpenCountAfterStart: NumberStats;
	eventSourceTransientIdCountAfterStart: NumberStats;
	sseTextEventCount: NumberStats;
	sseReasoningEventCount: NumberStats;
	sseChunkBytesP50: NumberStats;
	sseChunkGapP90Ms: NumberStats;
	sseTextEventsPerChunkP90: NumberStats;
	sseTextEventGapP90Ms: NumberStats;
	sseFirstTextEventMs: NumberStats;
	selectedLiveTextEventCountAfterStart: NumberStats;
	selectedLiveReasoningEventCountAfterStart: NumberStats;
	selectedLiveEventCountAfterStart: NumberStats;
	selectedLiveForcedCloseCountAfterStart: NumberStats;
	selectedLiveReconnectOpenCountAfterStart: NumberStats;
	selectedLiveTransientIdCountAfterStart: NumberStats;
	selectedLiveLiveSinceCount: NumberStats;
	selectedLiveReplayEventCountAfterStart: NumberStats;
	selectedLiveReplayCursorLagMaxAfterStart: NumberStats;
	selectedLiveReplayDuplicateCountAfterStart: NumberStats;
	selectedLiveReplayMissedCountAfterStart: NumberStats;
	selectedLiveFirstTextEventMsAfterStart: NumberStats;
	roomSummaryEventCountAfterStart: NumberStats;
	roomSummaryTextEventCountAfterStart: NumberStats;
	roomSummaryReasoningEventCountAfterStart: NumberStats;
	providerTextDeltaCount: NumberStats;
	providerReasoningDeltaCount: NumberStats;
	providerTextDeltaBytesP50: NumberStats;
	providerTextDeltaGapP90Ms: NumberStats;
	providerFirstTextLatencyMs: NumberStats;
	providerParseErrorCount: NumberStats;
	providerUnknownEventCount: NumberStats;
	providerSseTextRatio: NumberStats;
	providerSseReasoningRatio: NumberStats;
	providerSelectedLiveTextRatio: NumberStats;
	providerSelectedLiveReasoningRatio: NumberStats;
	providerDomPositiveTextRatio: NumberStats;
};

export type StreamingNegativeProfile = "batch" | "overlay-drop";

export type StreamingBenchmarkComparison = {
	baselineRuns: number;
	currentRuns: number;
	smoothnessDelta?: number;
	domGapP90DeltaMs?: number;
	domPositiveUpdateDelta?: number;
	domJumpMaxDeltaChars?: number;
	longTaskMaxDeltaMs?: number;
	firstVisibleDeltaMs?: number;
	liveFirstTextDeltaDeltaMs?: number;
	liveFirstEnqueueDeltaMs?: number;
	liveFirstFlushDeltaMs?: number;
	liveFirstOverlayUpdateDeltaMs?: number;
	sseFirstTextEventDeltaMs?: number;
	selectedLiveFirstTextEventDeltaMs?: number;
	providerFirstTextLatencyDeltaMs?: number;
	debugEnqueueCountDelta?: number;
	debugFlushCountDelta?: number;
	debugOverlayUpdateCountDelta?: number;
	debugTraceRefreshCompletedCountDelta?: number;
	liveEnqueueToExpectedRatioDelta?: number;
	liveFlushedEventsToExpectedRatioDelta?: number;
	liveOverlayEventsToExpectedRatioDelta?: number;
	liveFlushToEnqueueRatioDelta?: number;
	liveOverlayUpdatesToFlushedEventsRatioDelta?: number;
	traceLiveVersionCountDelta?: number;
	traceMaxAssistantOutputDelta?: number;
	traceDurableEventDeltaDelta?: number;
	fixtureScheduleGapP90DeltaMs?: number;
	domLagOverFixtureScheduleP90DeltaMs?: number;
	sseTextLagOverFixtureScheduleP90DeltaMs?: number;
	eventSourceTextEventDelta?: number;
	eventSourceReasoningEventDelta?: number;
	sseTextEventDelta?: number;
	sseChunkGapP90DeltaMs?: number;
	selectedLiveTextEventDelta?: number;
	selectedLiveReasoningEventDelta?: number;
	selectedLiveEventDelta?: number;
	providerSseTextRatioDelta?: number;
	providerSelectedLiveTextRatioDelta?: number;
	providerSseReasoningRatioDelta?: number;
	providerSelectedLiveReasoningRatioDelta?: number;
	providerDomPositiveTextRatioDelta?: number;
};

export type StreamingBenchmarkAssertion = {
	expectedRegressionPatterns: string[];
	expectedRegressions: string[];
	unexpectedRegressions: string[];
	missingExpectedRegressionPatterns: string[];
	passed: boolean;
};

export type StreamingBenchmarkGroup = {
	kind: "streaming-benchmark-runs";
	createdAt: string;
	durationMs: number;
	runs: StreamingBenchmark[];
	negativeProfile?: StreamingNegativeProfile;
	summary: StreamingBenchmarkSummary;
	comparison?: StreamingBenchmarkComparison;
	regressions: string[];
	warnings: string[];
	assertion?: StreamingBenchmarkAssertion;
};

export type StreamingBenchmarkUrlComparison = {
	kind: "streaming-benchmark-url-comparison";
	createdAt: string;
	durationMs: number;
	primaryUrl: string;
	compareUrl: string;
	primary: StreamingBenchmarkGroup;
	compare: StreamingBenchmarkGroup;
	negativeProfile?: StreamingNegativeProfile;
	comparison: StreamingBenchmarkComparison;
	regressions: string[];
	warnings: string[];
	assertion?: StreamingBenchmarkAssertion;
};

export type StreamingBenchmarkReportRow = {
	section: "compact" | "compact-url-comparison";
	metric: string;
	preservation?: string;
	cadenceLatency?: string;
	primaryP50?: string;
	compareP50?: string;
	delta?: string;
};
