import { PiboWebHttpError, readJsonBody, responseJson } from '../../web/http.js';
import type { PiboWebAppContext, PiboWebSession } from '../../web/types.js';
import { getPiboRalphService } from '../../ralph/channel.js';
import { listRalphJobTemplates } from '../../ralph/templates.js';
import type { ModelProfile } from '../../core/profiles.js';
import { isPiboThinkingLevel, type PiboThinkingLevel } from '../../core/thinking.js';
import type { PiboRalphJob, PiboRalphJobPatchInput, PiboRalphRun, PiboRalphStopPolicy, PiboRalphTarget } from '../../ralph/types.js';
import { normalizeRalphStopPolicy, type PiboRalphStore } from '../../ralph/store.js';
import { isPiboRoomArchived, type PiboRoom, type PiboRoomNode } from './types/rooms.js';
const CHAT_WEB_API_PREFIX = '/api/chat';
type ChatRoomActions = { getRoom(id: string): PiboRoom | undefined; listRoomTree(): PiboRoomNode[]; requireRoom(roomId: string): PiboRoom; ensureDefaultRoom(input?: { name?: string }): PiboRoom };
export type ChatRalphApiOptions = { request: Request; context: PiboWebAppContext; webSession: PiboWebSession; roomService: ChatRoomActions; ralphStore: PiboRalphStore; defaultProfile: string };
type RalphJobBody = { name?: unknown; description?: unknown; enabled?: unknown; target?: unknown; profile?: unknown; prompt?: unknown; maxIterations?: unknown; stopPolicy?: unknown; modelOverride?: unknown; thinkingLevel?: unknown; fastMode?: unknown };
function requireSameOriginJsonRequest(request: Request): void { const contentType = request.headers.get('content-type')?.split(';')[0]?.trim().toLowerCase(); if (contentType !== 'application/json') throw new PiboWebHttpError('Content-Type must be application/json', 415); const origin = request.headers.get('origin'); if (!origin) throw new PiboWebHttpError('Origin header is required', 403); if (origin !== new URL(request.url).origin) throw new PiboWebHttpError('Origin is not allowed', 403); }
function accessDenied(error: unknown): never { throw new PiboWebHttpError(error instanceof Error ? error.message : 'Access denied', 403); }
function normalizeString(value: unknown, field: string, options: { required?: boolean; max?: number } = {}): string | undefined { if (value === undefined || value === null) { if (options.required) throw new PiboWebHttpError(`${field} is required`, 400); return undefined; } if (typeof value !== 'string') throw new PiboWebHttpError(`${field} must be a string`, 400); const normalized = value.trim(); if (!normalized && options.required) throw new PiboWebHttpError(`${field} is required`, 400); if (options.max && normalized.length > options.max) throw new PiboWebHttpError(`${field} is too long`, 400); return normalized || undefined; }
function normalizeEnabled(value: unknown): boolean | undefined { if (value === undefined) return undefined; if (typeof value !== 'boolean') throw new PiboWebHttpError('enabled must be a boolean', 400); return value; }
function normalizeMaxIterations(value: unknown): number | undefined { if (value === undefined || value === null || value === '') return undefined; if (typeof value !== 'number' || !Number.isInteger(value) || value < 1) throw new PiboWebHttpError('maxIterations must be a positive integer', 400); return value; }
function normalizeStopPolicy(value: unknown): PiboRalphStopPolicy | undefined { if (value === undefined || value === null) return undefined; try { return normalizeRalphStopPolicy(value as PiboRalphStopPolicy); } catch (error) { throw new PiboWebHttpError(error instanceof Error ? error.message : 'Invalid stopPolicy', 400); } }
function normalizeModelOverride(value: unknown): ModelProfile | undefined { if (value === undefined || value === null) return undefined; if (!value || typeof value !== 'object' || Array.isArray(value)) throw new PiboWebHttpError('modelOverride must be an object', 400); const raw = value as Record<string, unknown>; if (typeof raw.provider !== 'string' || typeof raw.id !== 'string') throw new PiboWebHttpError('modelOverride must include provider and id', 400); const provider = raw.provider.trim(); const id = raw.id.trim(); if (!provider || !id) throw new PiboWebHttpError('modelOverride must include provider and id', 400); return { provider, id }; }
function normalizeThinkingLevel(value: unknown): PiboThinkingLevel | undefined { if (value === undefined || value === null || value === '') return undefined; if (typeof value !== 'string' || !isPiboThinkingLevel(value)) throw new PiboWebHttpError('thinkingLevel must be one of off, minimal, low, medium, high, xhigh', 400); return value; }
function normalizeFastMode(value: unknown): boolean | undefined { if (value === undefined || value === null) return undefined; if (typeof value !== 'boolean') throw new PiboWebHttpError('fastMode must be a boolean', 400); return value; }
function normalizeTarget(value: unknown, options: ChatRalphApiOptions): PiboRalphTarget { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new PiboWebHttpError('target is required', 400); const raw = value as { kind?: unknown; roomId?: unknown }; if (raw.kind === 'room') { const roomId = normalizeString(raw.roomId, 'target.roomId', { required: true })!; let room: PiboRoom; try { room = options.roomService.requireRoom(roomId); } catch (error) { accessDenied(error); } if (isPiboRoomArchived(room)) throw new PiboWebHttpError('Archived rooms are read-only', 403); return { kind: 'room', roomId }; } if (raw.kind === 'default-chat') { options.roomService.ensureDefaultRoom({ name: 'Shared Chat' }); return { kind: 'default-chat' }; } throw new PiboWebHttpError('target.kind must be room or default-chat', 400); }
function resolveProfile(context: PiboWebAppContext, fallback: string, value: unknown): string { const requested = normalizeString(value, 'profile') ?? fallback; const profile = context.channelContext.getProfiles?.().find((item) => item.name === requested || item.aliases.includes(requested)); if (!profile) throw new PiboWebHttpError(`Unknown profile: ${requested}`, 400); return profile.name; }
function jobResource(pathname: string): { id: string; child?: 'start' | 'stop' | 'cancel' } | undefined { const prefix = `${CHAT_WEB_API_PREFIX}/ralph/jobs/`; if (!pathname.startsWith(prefix)) return undefined; const parts = pathname.slice(prefix.length).split('/').filter(Boolean).map((part) => decodeURIComponent(part)); if (!parts[0] || parts.length > 2) return undefined; if (parts[1] && !['start', 'stop', 'cancel'].includes(parts[1])) return undefined; return { id: parts[0], child: parts[1] as 'start' | 'stop' | 'cancel' | undefined }; }
function createPatch(body: RalphJobBody, options: ChatRalphApiOptions): PiboRalphJobPatchInput { const patch: PiboRalphJobPatchInput = {}; const name = normalizeString(body.name, 'name', { max: 120 }); if (body.name !== undefined && name !== undefined) patch.name = name; if (body.description !== undefined) patch.description = normalizeString(body.description, 'description', { max: 500 }); const enabled = normalizeEnabled(body.enabled); if (enabled !== undefined) patch.enabled = enabled; if (body.target !== undefined) patch.target = normalizeTarget(body.target, options); if (body.profile !== undefined) patch.profile = resolveProfile(options.context, options.defaultProfile, body.profile); if (body.prompt !== undefined) patch.prompt = normalizeString(body.prompt, 'prompt', { required: true, max: 20_000 }); if (body.maxIterations !== undefined) patch.maxIterations = normalizeMaxIterations(body.maxIterations) ?? null; if (body.stopPolicy !== undefined) patch.stopPolicy = normalizeStopPolicy(body.stopPolicy) ?? null; if (body.modelOverride !== undefined) patch.modelOverride = normalizeModelOverride(body.modelOverride) ?? null; if (body.thinkingLevel !== undefined) patch.thinkingLevel = normalizeThinkingLevel(body.thinkingLevel) ?? null; if (body.fastMode !== undefined) patch.fastMode = normalizeFastMode(body.fastMode) ?? null; if (Object.keys(patch).length === 0) throw new PiboWebHttpError('No Ralph job update fields provided', 400); return patch; }

type RalphApiTarget = { kind: 'room'; roomId: string } | { kind: 'default-chat' };
type RalphApiJob = Omit<PiboRalphJob, 'target'> & { target: RalphApiTarget };
type RalphApiRun = PiboRalphRun;
function serializeTarget(target: PiboRalphTarget): RalphApiTarget { return target.kind === 'room' ? target : { kind: 'default-chat' }; }
function serializeJob(job: PiboRalphJob): RalphApiJob { const { target, ...rest } = job; return { ...rest, target: serializeTarget(target) }; }
function serializeRun(run: PiboRalphRun): RalphApiRun { return run; }
export async function handleChatRalphApiRequest(options: ChatRalphApiOptions): Promise<Response | undefined> {
	const { request, ralphStore } = options; const url = new URL(request.url); if (!url.pathname.startsWith(`${CHAT_WEB_API_PREFIX}/ralph`)) return undefined;
	if (url.pathname === `${CHAT_WEB_API_PREFIX}/ralph/status` && request.method === 'GET') return responseJson({ status: getPiboRalphService()?.status() ?? { enabled: false, ...ralphStore.status() } });
	if (url.pathname === `${CHAT_WEB_API_PREFIX}/ralph/conditions` && request.method === 'GET') return responseJson({ conditions: options.context.channelContext.getRalphStopConditionInfos?.() ?? options.context.channelContext.getCapabilityCatalog?.().ralphStopConditions ?? [] });
	if (url.pathname === `${CHAT_WEB_API_PREFIX}/ralph/templates` && request.method === 'GET') return responseJson({ templates: listRalphJobTemplates() });
	if (url.pathname === `${CHAT_WEB_API_PREFIX}/ralph/jobs` && request.method === 'GET') return responseJson({ jobs: ralphStore.listJobs({ includeDisabled: url.searchParams.get('includeDisabled') === 'true' }).map(serializeJob) });
	if (url.pathname === `${CHAT_WEB_API_PREFIX}/ralph/jobs` && request.method === 'POST') { requireSameOriginJsonRequest(request); const body = await readJsonBody<RalphJobBody>(request); const job = ralphStore.createJob({ name: normalizeString(body.name, 'name', { max: 120 }), description: normalizeString(body.description, 'description', { max: 500 }), enabled: normalizeEnabled(body.enabled), target: normalizeTarget(body.target, options), profile: resolveProfile(options.context, options.defaultProfile, body.profile), prompt: normalizeString(body.prompt, 'prompt', { required: true, max: 20_000 })!, maxIterations: normalizeMaxIterations(body.maxIterations), stopPolicy: normalizeStopPolicy(body.stopPolicy), modelOverride: normalizeModelOverride(body.modelOverride), thinkingLevel: normalizeThinkingLevel(body.thinkingLevel), fastMode: normalizeFastMode(body.fastMode) }); return responseJson({ job: serializeJob(job) }, { status: 201 }); }
	if (url.pathname === `${CHAT_WEB_API_PREFIX}/ralph/runs` && request.method === 'GET') { const jobId = url.searchParams.get('jobId') || undefined; const limit = Number(url.searchParams.get('limit') ?? '100'); if (jobId && !ralphStore.getJob(jobId)) throw new PiboWebHttpError('Ralph job not found', 404); return responseJson({ runs: ralphStore.listRuns({ jobId, limit: Number.isFinite(limit) ? limit : 100 }).map(serializeRun) }); }
	const resource = jobResource(url.pathname); if (!resource) return undefined;
	if (resource.child && request.method === 'POST') { requireSameOriginJsonRequest(request); const service = getPiboRalphService(); if (!service) throw new PiboWebHttpError('Ralph service is not running', 503); if (resource.child === 'start') { const run = await service.startJob(resource.id); if (!run) throw new PiboWebHttpError('Ralph job not found, already running, or stopped by a before-run condition', 404); return responseJson({ run: serializeRun(run) }, { status: 202 }); } if (resource.child === 'stop') { const job = service.stopJob(resource.id); if (!job) throw new PiboWebHttpError('Ralph job not found', 404); return responseJson({ job: serializeJob(job) }); } const job = await service.cancelJob(resource.id); if (!job) throw new PiboWebHttpError('Ralph job not found', 404); return responseJson({ job: serializeJob(job) }); }
	if (resource.child) return undefined;
	if (request.method === 'GET') { const job = ralphStore.getJob(resource.id); if (!job) throw new PiboWebHttpError('Ralph job not found', 404); return responseJson({ job: serializeJob(job) }); }
	if (request.method === 'PATCH') { requireSameOriginJsonRequest(request); const body = await readJsonBody<RalphJobBody>(request); const job = ralphStore.updateJob(resource.id, createPatch(body, options)); if (!job) throw new PiboWebHttpError('Ralph job not found', 404); return responseJson({ job: serializeJob(job) }); }
	if (request.method === 'DELETE') { requireSameOriginJsonRequest(request); return responseJson({ removed: ralphStore.removeJob(resource.id) }); }
	return undefined;
}
