export type CodexAppServerJson =
	| null
	| boolean
	| number
	| string
	| CodexAppServerJson[]
	| { [key: string]: CodexAppServerJson };

export type CodexAppServerRequestId = string | number;

export type CodexAppServerClientInfo = {
	name: string;
	title?: string | null;
	version: string;
};

/** Stable initialize capabilities generated by Codex App Server 0.147.0. */
export type CodexAppServerInitializeCapabilities = {
	experimentalApi?: boolean;
	extensions?: Record<string, CodexAppServerJson> | null;
	mcpServerOpenaiFormElicitation?: boolean;
	optOutNotificationMethods?: string[] | null;
	requestAttestation?: boolean;
};

export type CodexAppServerInitializeParams = {
	clientInfo: CodexAppServerClientInfo;
	capabilities?: CodexAppServerInitializeCapabilities | null;
};

export type CodexAppServerInitializeResponse = {
	codexHome: string;
	platformFamily: string;
	platformOs: string;
	userAgent: string;
};

/** Stable Codex App Server 0.147.0 account/read contract. */
export type CodexAppServerAccount =
	| { type: "apiKey" }
	| { type: "chatgpt"; email: string | null; planType: string }
	| { type: "amazonBedrock"; usesCodexManagedCredentials?: boolean };

export type CodexAppServerAccountReadParams = {
	refreshToken?: boolean;
};

export type CodexAppServerAccountReadResponse = {
	account?: CodexAppServerAccount | null;
	requiresOpenaiAuth: boolean;
};

/** Only the stable managed login modes Pibo supports. */
export type CodexAppServerAccountLoginStartParams =
	| { type: "apiKey"; apiKey: string }
	| { type: "chatgptDeviceCode" };

export type CodexAppServerAccountLoginStartResponse =
	| { type: "apiKey" }
	| { type: "chatgptDeviceCode"; loginId: string; userCode: string; verificationUrl: string };

export type CodexAppServerAccountLoginCompletedNotification = {
	success: boolean;
	loginId?: string | null;
	error?: string | null;
};

export type CodexAppServerAccountLoginCancelParams = {
	loginId: string;
};

export type CodexAppServerAccountLoginCancelResponse = {
	status: "canceled" | "notFound";
};

export type CodexAppServerAccountLogoutResponse = Record<string, never>;

export type CodexAppServerRpcError = {
	code: number;
	message: string;
	data?: CodexAppServerJson;
};

export type CodexAppServerClientRequest<TParams = CodexAppServerJson> = {
	id: CodexAppServerRequestId;
	method: string;
	params?: TParams;
};

export type CodexAppServerClientNotification<TParams = CodexAppServerJson> = {
	method: string;
	params?: TParams;
};

export type CodexAppServerSuccessResponse<TResult = CodexAppServerJson> = {
	id: CodexAppServerRequestId;
	result: TResult;
};

export type CodexAppServerErrorResponse = {
	id: CodexAppServerRequestId;
	error: CodexAppServerRpcError;
};

export type CodexAppServerResponse<TResult = CodexAppServerJson> =
	| CodexAppServerSuccessResponse<TResult>
	| CodexAppServerErrorResponse;

export type CodexAppServerServerRequest<TParams = CodexAppServerJson> = {
	id: CodexAppServerRequestId;
	method: string;
	params?: TParams;
};

export type CodexAppServerServerNotification<TParams = CodexAppServerJson> = {
	method: string;
	params?: TParams;
};

export type CodexAppServerThreadStatus =
	| { type: "notLoaded" }
	| { type: "idle" }
	| { type: "systemError" }
	| { type: "active"; activeFlags: string[] };

export type CodexAppServerTurnStatus = "completed" | "interrupted" | "failed" | "inProgress";

export type CodexAppServerThreadItem = {
	id: string;
	type: string;
} & Record<string, unknown>;

export type CodexAppServerTurn = {
	id: string;
	status: CodexAppServerTurnStatus;
	items: CodexAppServerThreadItem[];
	itemsView?: "notLoaded" | "summary" | "full";
	startedAt?: number | null;
	completedAt?: number | null;
	durationMs?: number | null;
	error?: unknown;
};

export type CodexAppServerTextUserInput = {
	type: "text";
	text: string;
	text_elements?: unknown[];
};

export type CodexAppServerUserInput =
	| CodexAppServerTextUserInput
	| ({ type: "image"; url: string; detail?: string | null })
	| ({ type: "localImage"; path: string; detail?: string | null })
	| ({ type: "audio"; url: string })
	| ({ type: "localAudio"; path: string })
	| ({ type: "skill" | "mention"; name: string; path: string });

export type CodexAppServerTurnStartParams = {
	threadId: string;
	input: CodexAppServerUserInput[];
	clientUserMessageId?: string | null;
	cwd?: string | null;
	approvalPolicy?: unknown;
	approvalsReviewer?: unknown;
	sandboxPolicy?: unknown;
	model?: string | null;
	effort?: string | null;
	summary?: string | null;
	serviceTier?: string | null;
	personality?: string | null;
	outputSchema?: CodexAppServerJson;
};

export type CodexAppServerTurnStartResponse = {
	turn: CodexAppServerTurn;
};

export type CodexAppServerTurnSteerParams = {
	threadId: string;
	expectedTurnId: string;
	input: CodexAppServerUserInput[];
	clientUserMessageId?: string | null;
};

export type CodexAppServerTurnSteerResponse = {
	turnId: string;
};

export type CodexAppServerTurnInterruptParams = {
	threadId: string;
	turnId: string;
};

export type CodexAppServerTurnInterruptResponse = Record<string, never>;

export type CodexAppServerReasoningEffortOption = {
	reasoningEffort: string;
	description: string;
};

export type CodexAppServerModelServiceTier = {
	id: string;
	name: string;
	description: string;
};

export type CodexAppServerModel = {
	id: string;
	model: string;
	displayName: string;
	description: string;
	hidden: boolean;
	isDefault: boolean;
	supportedReasoningEfforts: CodexAppServerReasoningEffortOption[];
	defaultReasoningEffort: string;
	serviceTiers: CodexAppServerModelServiceTier[];
	defaultServiceTier?: string | null;
	inputModalities?: string[];
	supportsPersonality?: boolean;
	modelSpecialty?: string | null;
	upgrade?: string | null;
};

export type CodexAppServerModelListParams = {
	cursor?: string | null;
	limit?: number | null;
	includeHidden?: boolean | null;
};

export type CodexAppServerModelListResponse = {
	data: CodexAppServerModel[];
	nextCursor?: string | null;
};

export type CodexAppServerThreadSettings = {
	model: string;
	modelProvider: string;
	serviceTier?: string | null;
	effort?: string | null;
	summary?: string | null;
	personality?: string | null;
} & Record<string, unknown>;

export type CodexAppServerThreadSettingsUpdatedNotification = {
	threadId: string;
	threadSettings: CodexAppServerThreadSettings;
};

export type CodexAppServerModelReroutedNotification = {
	threadId: string;
	turnId: string;
	fromModel: string;
	toModel: string;
	reason: unknown;
};

export type CodexAppServerSkillsExtraRootsSetParams = {
	extraRoots: string[];
};

export type CodexAppServerSkillsExtraRootsSetResponse = Record<string, never>;

export type CodexAppServerSkillMetadata = {
	name: string;
	description: string;
	enabled: boolean;
	path: string;
	scope: string;
};

export type CodexAppServerSkillsListResponse = {
	data: Array<{
		cwd: string;
		skills: CodexAppServerSkillMetadata[];
		errors: unknown[];
	}>;
};

export type CodexAppServerMcpServerStatus = {
	name: string;
	tools: Record<string, unknown>;
	resources: unknown[];
	resourceTemplates: unknown[];
	authStatus: unknown;
	serverInfo?: unknown;
};

export type CodexAppServerListMcpServerStatusResponse = {
	data: CodexAppServerMcpServerStatus[];
	nextCursor?: string | null;
};

export type CodexAppServerApprovalDecision = "accept" | "acceptForSession" | "decline" | "cancel";

export type CodexAppServerCommandApprovalParams = {
	threadId: string;
	turnId: string;
	itemId: string;
	startedAtMs: number;
	approvalId?: string | null;
	environmentId?: string | null;
	reason?: string | null;
	command?: string | null;
	cwd?: string | null;
	commandActions?: unknown[] | null;
	networkApprovalContext?: unknown;
	proposedExecpolicyAmendment?: string[] | null;
	proposedNetworkPolicyAmendments?: unknown[] | null;
};

export type CodexAppServerFileChangeApprovalParams = {
	threadId: string;
	turnId: string;
	itemId: string;
	startedAtMs: number;
	reason?: string | null;
	grantRoot?: string | null;
};

export type CodexAppServerApprovalResponse = {
	decision: CodexAppServerApprovalDecision;
};

export type CodexAppServerUserInputOption = {
	label: string;
	description: string;
};

export type CodexAppServerUserInputQuestion = {
	id: string;
	header: string;
	question: string;
	isOther?: boolean;
	isSecret?: boolean;
	options?: CodexAppServerUserInputOption[] | null;
};

export type CodexAppServerUserInputRequestParams = {
	threadId: string;
	turnId: string;
	itemId: string;
	questions: CodexAppServerUserInputQuestion[];
	isBlocking: boolean;
	autoResolutionMs?: number | null;
};

export type CodexAppServerUserInputResponse = {
	answers: Record<string, { answers: string[] }>;
};

export type CodexAppServerServerRequestResolvedNotification = {
	threadId: string;
	requestId: CodexAppServerRequestId;
};

export type CodexAppServerTokenUsageBreakdown = {
	cacheWriteInputTokens?: number;
	cachedInputTokens: number;
	inputTokens: number;
	outputTokens: number;
	reasoningOutputTokens: number;
	totalTokens: number;
};

export type CodexAppServerThreadTokenUsage = {
	last: CodexAppServerTokenUsageBreakdown;
	total: CodexAppServerTokenUsageBreakdown;
	modelContextWindow?: number | null;
};

export type CodexAppServerThreadTokenUsageUpdatedNotification = {
	threadId: string;
	turnId: string;
	tokenUsage: CodexAppServerThreadTokenUsage;
};

export type CodexAppServerThread = {
	id: string;
	preview: string;
	modelProvider: string;
	createdAt: number;
	updatedAt: number;
	recencyAt?: number | null;
	cwd: string;
	cliVersion: string;
	source: unknown;
	threadSource?: unknown;
	status: CodexAppServerThreadStatus;
	ephemeral: boolean;
	turns: CodexAppServerTurn[];
	sessionId: string;
	name?: string | null;
	forkedFromId?: string | null;
	parentThreadId?: string | null;
	path?: string | null;
};

export type CodexAppServerThreadStartParams = {
	cwd?: string | null;
	ephemeral?: boolean | null;
	model?: string | null;
	modelProvider?: string | null;
	serviceTier?: string | null;
	personality?: string | null;
	config?: Record<string, CodexAppServerJson> | null;
	baseInstructions?: string | null;
	developerInstructions?: string | null;
	approvalPolicy?: string | null;
	sandbox?: string | null;
};

export type CodexAppServerThreadResumeParams = Omit<CodexAppServerThreadStartParams, "ephemeral"> & {
	threadId: string;
};

export type CodexAppServerThreadForkParams = CodexAppServerThreadStartParams & {
	threadId: string;
	lastTurnId?: string | null;
	ephemeral?: boolean;
};

export type CodexAppServerThreadResponse = {
	thread: CodexAppServerThread;
	model: string;
	modelProvider: string;
	cwd: string;
	reasoningEffort?: string | null;
	serviceTier?: string | null;
	approvalPolicy: unknown;
	approvalsReviewer: unknown;
	sandbox: unknown;
	instructionSources?: string[];
};

export type CodexAppServerThreadReadParams = {
	threadId: string;
	includeTurns?: boolean;
};

export type CodexAppServerThreadReadResponse = {
	thread: CodexAppServerThread;
};

export type CodexAppServerThreadInjectItemsParams = {
	threadId: string;
	items: CodexAppServerJson[];
};

export type CodexAppServerThreadInjectItemsResponse = Record<string, never>;

export type CodexAppServerThreadCompactStartParams = {
	threadId: string;
};

export type CodexAppServerThreadCompactStartResponse = Record<string, never>;

export type CodexAppServerThreadSourceKind =
	| "cli"
	| "vscode"
	| "exec"
	| "appServer"
	| "subAgent"
	| "subAgentReview"
	| "subAgentCompact"
	| "subAgentThreadSpawn"
	| "subAgentOther"
	| "unknown";

export type CodexAppServerThreadListParams = {
	cursor?: string | null;
	limit?: number | null;
	sortKey?: "created_at" | "updated_at" | "recency_at" | "section_position" | null;
	sortDirection?: "asc" | "desc" | null;
	cwd?: string | string[] | null;
	archived?: boolean | null;
	sourceKinds?: CodexAppServerThreadSourceKind[] | null;
};

export type CodexAppServerThreadListResponse = {
	data: CodexAppServerThread[];
	nextCursor?: string | null;
	backwardsCursor?: string | null;
};
